apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-api
  labels:
    app: backoffice-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backoffice-api
  template:
    metadata:
      labels:
        app: backoffice-api
    spec:
      containers:
      - name: backoffice-api
        image: gcr.io/${PROJECT_ID}/backoffice-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: backoffice-api-secrets
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: backoffice-api-secrets
              key: db-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backoffice-api-secrets
              key: db-password
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backoffice-api
spec:
  selector:
    app: backoffice-api
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer 