apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fintech-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.your-domain.com
    - backoffice.your-domain.com
    secretName: fintech-tls
  rules:
  - host: api.your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: payment-api-service
            port:
              number: 80
  - host: backoffice.your-domain.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backoffice-api-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backoffice-manage-service
            port:
              number: 80 