apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: ${NAMESPACE}
  labels:
    app: payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
      - name: payment-api
        image: ${DOCKER_REGISTRY}/payment-api:${IMAGE_TAG}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "${SPRING_PROFILE}"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: payment-api-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: payment-api
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP 