apiVersion: v1
kind: Service
metadata:
  name: backoffice-api
  labels:
    app: backoffice-api
spec:
  selector:
    app: backoffice-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backoffice-api-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - admin-api.passionpay.com
    secretName: backoffice-api-tls
  rules:
  - host: admin-api.passionpay.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backoffice-api
            port:
              number: 80 