apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: ${NAMESPACE}
  labels:
    app: payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-api
  strategy:
    type: Recreate
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
      - name: payment-api
        image: ${DOCKER_REGISTRY}/payment-api:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "${SPRING_PROFILE}"
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx512m" 